import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/app/components/server/Navigation";
import Footer from "@/app/components/server/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <div className="container mx-auto px-5">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
